server:
  port: ${SERVER_PORT:${PORT:3577}}

spring:
  application:
    name: devshowcase-api
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/devshowcase}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        format_sql: false
    show-sql: false

springdoc:
  swagger-ui:
    path: /api/docs
  api-docs:
    path: /api/docs/api-docs
